
"clusterName": "eks-blueprint-blue"
"region": "eu-west-1"
"repoUrl": "https://github.com/PeculiarGideon/eks-blueprints-workloads.git"
"spec":
  "apps":
    "ecsdemoFrontend":
      "image":
        "repository": "public.ecr.aws/seb-demo/ecsdemo-frontend"
        "tag": "latest"
      "ingress":
        "annotations": |
          "alb.ingress.kubernetes.io/group.name": "ecsdemo"
          "alb.ingress.kubernetes.io/listen-ports": "[{\"HTTP\": 443}]"
          "alb.ingress.kubernetes.io/scheme": "internet-facing"
          "alb.ingress.kubernetes.io/ssl-redirect": "443"
          "alb.ingress.kubernetes.io/target-type": "ip"
          "external-dns.alpha.kubernetes.io/aws-weight": "100"
          "external-dns.alpha.kubernetes.io/set-identifier": "eks-blueprint-blue"
        "className": "alb"
        "enabled": "true"
        "hosts":
        - "host": "frontend.eks-blueprint.example.com"
          "paths":
          - "path": "/"
            "pathType": "Prefix"
      "replicaCount": "3"
      "resources":
        "limits":
          "cpu": "400m"
          "memory": "512Mi"
        "requests":
          "cpu": "200m"
          "memory": "256Mi"
    "generalInsurance":
      "image":
        "repository": "registry.hub.docker.com/r/mastsurfeit/gi"
        "tag": "latest"
      "ingress":
        "annotations": |
          "alb.ingress.kubernetes.io/group.name": "ecsdemo"
          "alb.ingress.kubernetes.io/listen-ports": "[{\"HTTP\": 80}]"
          "alb.ingress.kubernetes.io/scheme": "internet-facing"
          "alb.ingress.kubernetes.io/ssl-redirect": "80"
          "alb.ingress.kubernetes.io/target-type": "ip"
          "external-dns.alpha.kubernetes.io/aws-weight": "100"
          "external-dns.alpha.kubernetes.io/set-identifier": "eks-blueprint-blue"
        "className": "alb"
        "enabled": "true"
        "hosts":
        - "host": "localhost:8080"
          "paths":
          - "path": "/hello"
            "pathType": "Prefix"
      "replicaCount": "3"
      "resources":
        "limits":
          "cpu": "400m"
          "memory": "512Mi"
        "requests":
          "cpu": "200m"
          "memory": "256Mi"   
  "blueprint": "terraform"
  "clusterName": "eks-blueprint-blue"
  "karpenterInstanceProfile": "eks-blueprint-blue-managed-ondemand"
