spec:
  destination:
    server: https://kubernetes.default.svc
  # All helm parameters are sent by IaC code (Terraform or CDK)
  apps:
    ecsdemoFrontend:
      repoURL: https://github.com/aws-containers/ecsdemo-frontend.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-frontend
      ingress:
        enabled: 'true'
        className: 'alb'
        annotations:
          'alb.ingress.kubernetes.io/group.name': 'ecsdemo'
          'alb.ingress.kubernetes.io/scheme': 'internet-facing'
          'alb.ingress.kubernetes.io/target-type': 'ip'
          'external-dns.alpha.kubernetes.io/set-identifier': 'eks-blueprint-blue'
        hosts:
          host: test.example.com
          paths:
            path: '/'
            pathType: 'Prefix'
    general-insurance:
      repoURL: https://github.com/PeculiarGideon/gi.git
      targetRevision: main
      path: kubernetes/helm/general-insurance
      ingress:
        enabled: 'true'
        className: 'alb'
        annotations:
          'alb.ingress.kubernetes.io/group.name': 'gi'
          'alb.ingress.kubernetes.io/scheme': 'internet-facing'
          'alb.ingress.kubernetes.io/target-type': 'ip'
          'external-dns.alpha.kubernetes.io/set-identifier': 'eks-blueprint-blue'
        hosts:
          host: test.example.com
          paths:
            path: '/hello'
            pathType: 'Prefix'        
    ecsdemoNodejs:
      repoURL: https://github.com/aws-containers/ecsdemo-nodejs.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-nodejs
    ecsdemoCrystal:
      repoURL: https://github.com/aws-containers/ecsdemo-crystal.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-crystal
